version: '3.8'

services:
  backend:
    build:
      context: ./springboot-backend
    ports:
      - "8088:8088"

  frontend:
    build:
      context: ./angular-frontend
    ports:
      - "4200:80"
